obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.22, -0.21], [-0.22, 0.21], [0.22, 0.21], [0.22, -0.21]]
robot_radius: 0.16
inflation_radius: 0.5
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: scan, marking: true, clearing: true}


