global_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 3.0
   publish_frequency: 1.5
   static_map: false
   rolling_window: true
   resolution: 0.05
   transform_tolerance: 3.0
   
