#Description:

 # move_base package now explain the meaning of each parameter in turn:

# shutdown_costmaps: Whether the costmap is turned off when move_base is inactive.

# controller_frequency: Controls the frequency at which the mobile theme cmd_vel sends commands to the chassis.

# controller_patience: How long the controller spends effective control before the space cleanup operation is performed.

# planner_frequency: The execution frequency of the global planning operation. If set to 0.0, the global planner only

# The re-execution operation will be performed when a new target point is received or the local planner reports that the path is blocked.

# planner_patience: How long to leave the planner to find an effective plan before the space cleanup operation is performed.

# oscillation_timeout: The length of time that the oscillation is allowed before the repair mechanism is executed.

# oscillation_distance: The distance between the back and forth movements is not considered to be an oscillation.

# base_local_planner: Specify the local planner plugin name for move_base.

# base_global_planner: Specify the global planner plugin name for move_base.


shutdown_costmaps: false


controller_frequency: 5.0
controller_patience: 3.0
 
planner_frequency: 1.0
planner_patience: 5.0

oscillation_timeout: 8.0
oscillation_distance: 0.3

 

base_local_planner: "dwa_local_planner/DWAPlannerROS"

base_global_planner: "global_planner/GlobalPlanner"